import { Platform } from '@agencyos/shared';

interface CheckDefinition {
  id: string;
  name: string;
  category: string;
  weight: number;
  description?: string;
  benchmark?: string;
  aiRewriteEnabled?: boolean;
}

export const PLATFORM_CHECKS: Record<string, CheckDefinition[]> = {
  [Platform.LINKEDIN]: [
    { id: 'li_photo', name: 'Profile photo', category: 'profile', weight: 3, description: 'Professional headshot, face fills 60%+ of frame', benchmark: 'Profiles with photos get 21x more views' },
    { id: 'li_banner', name: 'Custom banner image', category: 'profile', weight: 2, description: '1584×396px, brand-aligned, includes tagline or CTA' },
    { id: 'li_headline', name: 'Headline optimization', category: 'profile', weight: 4, description: '220 chars max, keyword-rich, value proposition not just job title', aiRewriteEnabled: true },
    { id: 'li_about', name: 'About section', category: 'profile', weight: 4, description: '2,000 chars, first 2 lines hook before "see more", includes CTA', aiRewriteEnabled: true },
    { id: 'li_url', name: 'Custom LinkedIn URL', category: 'profile', weight: 2, description: 'linkedin.com/in/firstname-lastname — no random numbers' },
    { id: 'li_featured', name: 'Featured section', category: 'profile', weight: 3, description: 'Top 3 pieces of content, lead magnet, or case study pinned' },
    { id: 'li_experience', name: 'Experience descriptions', category: 'content', weight: 3, description: 'Each role has 3+ bullet points with metrics and outcomes', aiRewriteEnabled: true },
    { id: 'li_skills', name: 'Skills & endorsements', category: 'profile', weight: 2, description: '50 skills listed, top 3 pinned match core expertise' },
    { id: 'li_recommendations', name: 'Recommendations', category: 'trust', weight: 3, description: '5+ recommendations received from credible connections' },
    { id: 'li_ssi', name: 'SSI score guidance', category: 'activity', weight: 3, description: 'Social Selling Index tips: profile, connections, insights, relationships' },
    { id: 'li_posting', name: 'Post frequency', category: 'activity', weight: 3, description: '3–5 posts/week, mix of text, carousels, videos, polls' },
    { id: 'li_engagement', name: 'Engagement rate', category: 'activity', weight: 3, description: 'Comment, like, and share ratio vs impressions' },
    { id: 'li_connections', name: 'Connection quality', category: 'network', weight: 2, description: '500+ connections, 2nd-degree reach to target audience' },
    { id: 'li_company_page', name: 'Company page presence', category: 'brand', weight: 3, description: 'Logo, cover, tagline, website, follower count, regular posts' },
    { id: 'li_content_mix', name: 'Content format variety', category: 'content', weight: 2, description: 'Mix of carousels (highest reach), text-only (high engagement), video, articles' },
  ],
  [Platform.INSTAGRAM]: [
    { id: 'ig_bio', name: 'Bio optimization', category: 'profile', weight: 4, description: '150 chars, keyword in name field, emoji breaks, link in bio tool', aiRewriteEnabled: true },
    { id: 'ig_profile_photo', name: 'Profile photo', category: 'profile', weight: 3, description: 'Logo centered, high contrast, recognizable at 40px' },
    { id: 'ig_highlights', name: 'Story highlights', category: 'content', weight: 3, description: '6–10 highlights, custom branded covers, strategic categories' },
    { id: 'ig_grid', name: 'Grid aesthetic', category: 'brand', weight: 3, description: 'Consistent color palette, alternating content types, brand cohesion' },
    { id: 'ig_reels', name: 'Reels presence', category: 'content', weight: 4, description: '3+ Reels/week, hook in first 3 seconds, trending audio' },
    { id: 'ig_captions', name: 'Caption strategy', category: 'content', weight: 3, description: 'First line hook, storytelling, CTA, 3–5 relevant hashtags in comments', aiRewriteEnabled: true },
    { id: 'ig_hashtags', name: 'Hashtag strategy', category: 'content', weight: 3, description: 'Mix of niche (10k–100k posts), mid (100k–1M), broad — not banned' },
    { id: 'ig_stories', name: 'Stories frequency', category: 'activity', weight: 3, description: '5–7 stories/day, interactive elements (polls, questions, sliders)' },
    { id: 'ig_engagement', name: 'Engagement rate', category: 'metrics', weight: 4, description: 'Benchmark: 3–6% for <10k followers, 1–3% for >100k' },
    { id: 'fb_page', name: 'Facebook page completeness', category: 'profile', weight: 3, description: 'All sections filled, CTA button set, services listed' },
    { id: 'fb_reviews', name: 'Facebook reviews', category: 'trust', weight: 3, description: '4.5+ rating, all reviews responded to, review link shared' },
    { id: 'fb_groups', name: 'Facebook group strategy', category: 'strategy', weight: 2, description: 'Brand group or active in niche groups' },
  ],
  [Platform.GBP]: [
    { id: 'gbp_claimed', name: 'Claimed & verified', category: 'setup', weight: 5 },
    { id: 'gbp_nap', name: 'NAP consistency', category: 'seo', weight: 4 },
    { id: 'gbp_category', name: 'Primary + secondary categories', category: 'setup', weight: 4 },
    { id: 'gbp_description', name: 'Business description', category: 'content', weight: 4, description: '750 chars, keyword-rich, service areas, unique differentiators', aiRewriteEnabled: true },
    { id: 'gbp_photos', name: 'Photo count & quality', category: 'content', weight: 3, description: '100+ photos: exterior, interior, team, products, work' },
    { id: 'gbp_posts', name: 'GBP post frequency', category: 'activity', weight: 3, description: 'Weekly posts: offers, events, products, updates' },
    { id: 'gbp_reviews', name: 'Review rating & volume', category: 'trust', weight: 5, description: '4.5+ avg, 50+ reviews, all responded to within 24h' },
    { id: 'gbp_review_responses', name: 'Review response quality', category: 'trust', weight: 3, description: 'Personalized, keyword-rich, not templated', aiRewriteEnabled: true },
    { id: 'gbp_qa', name: 'Q&A management', category: 'content', weight: 2 },
    { id: 'gbp_services', name: 'Services & menu', category: 'setup', weight: 3 },
    { id: 'gbp_attributes', name: 'Business attributes', category: 'setup', weight: 2 },
    { id: 'gbp_messaging', name: 'Messaging enabled', category: 'setup', weight: 2 },
  ],
  [Platform.YOUTUBE]: [
    { id: 'yt_channel_art', name: 'Channel art & branding', category: 'brand', weight: 3, description: '2560×1440px banner, logo watermark on all videos' },
    { id: 'yt_about', name: 'Channel description', category: 'profile', weight: 3, description: 'First 100 chars appear in search, keyword-rich, links included', aiRewriteEnabled: true },
    { id: 'yt_trailer', name: 'Channel trailer', category: 'content', weight: 3, description: '60–90 second trailer for unsubscribed visitors, clear hook & CTA' },
    { id: 'yt_playlists', name: 'Playlist organization', category: 'structure', weight: 3, description: '5+ playlists, keyword-rich titles, all videos categorized' },
    { id: 'yt_titles', name: 'Video title optimization', category: 'seo', weight: 4, description: '60 chars max, keyword-first, curiosity gap or clear benefit', aiRewriteEnabled: true },
    { id: 'yt_descriptions', name: 'Video descriptions', category: 'seo', weight: 4, description: '500+ words, keyword in first 2 sentences, timestamps, links, CTA', aiRewriteEnabled: true },
    { id: 'yt_tags', name: 'Tags & keywords', category: 'seo', weight: 3, description: '15–20 tags: exact match, broader terms, competitor terms' },
    { id: 'yt_thumbnails', name: 'Thumbnail quality', category: 'brand', weight: 4, description: 'Custom 1280×720px, high contrast, face + text, brand consistent' },
    { id: 'yt_upload_frequency', name: 'Upload frequency', category: 'activity', weight: 3, description: '1+ video/week, consistent schedule, community tab active' },
    { id: 'yt_cta', name: 'End screens & cards', category: 'conversion', weight: 3, description: 'End screen on all videos, cards linking to related content' },
    { id: 'yt_chapters', name: 'Video chapters', category: 'ux', weight: 2, description: 'Timestamps in description for videos 5+ minutes' },
    { id: 'yt_captions', name: 'Captions & subtitles', category: 'accessibility', weight: 2, description: 'Accurate captions on all videos, edited for correctness' },
  ],
  [Platform.TWITTER]: [
    { id: 'tw_bio', name: 'Bio optimization', category: 'profile', weight: 4, description: '160 chars, keywords, personality, pinned link', aiRewriteEnabled: true },
    { id: 'tw_header', name: 'Header image', category: 'brand', weight: 2, description: '1500×500px, brand-aligned, current campaign' },
    { id: 'tw_pinned', name: 'Pinned tweet', category: 'content', weight: 3, description: 'High-performing or evergreen content pinned, updated monthly' },
    { id: 'tw_posting', name: 'Tweet frequency', category: 'activity', weight: 3, description: '1–3 tweets/day, reply to relevant conversations, quote tweets' },
    { id: 'tw_threads', name: 'Thread quality', category: 'content', weight: 4, description: '1+ thread/week, strong hook, value-packed, numbered format', aiRewriteEnabled: true },
    { id: 'tw_engagement', name: 'Engagement rate', category: 'metrics', weight: 4, description: 'Likes + replies + retweets / impressions — benchmark 1–3%' },
    { id: 'tw_lists', name: 'Twitter/X lists', category: 'strategy', weight: 2, description: 'Curated lists for industry monitoring and competitor tracking' },
    { id: 'tw_spaces', name: 'X Spaces participation', category: 'activity', weight: 2, description: 'Host or co-host Spaces monthly for audience building' },
  ],
  [Platform.TIKTOK]: [
    { id: 'tt_bio', name: 'Bio & profile', category: 'profile', weight: 4, description: '80 chars bio, profile link enabled (1000+ followers), niche clear', aiRewriteEnabled: true },
    { id: 'tt_posting', name: 'Posting frequency', category: 'activity', weight: 4, description: '1–3 videos/day optimal, consistent time slots' },
    { id: 'tt_hook', name: 'Hook strength (first 3 seconds)', category: 'content', weight: 5, description: 'Pattern interrupt, curiosity, bold statement, or visual surprise' },
    { id: 'tt_captions', name: 'Caption & hashtags', category: 'content', weight: 3, description: '150 chars, 3–5 hashtags: 1 trending + 2 niche + 1 brand', aiRewriteEnabled: true },
    { id: 'tt_sounds', name: 'Trending audio usage', category: 'strategy', weight: 3, description: 'Using trending sounds within first 24h of trending increases reach 3x' },
    { id: 'tt_duet_stitch', name: 'Duet & stitch strategy', category: 'strategy', weight: 2, description: 'Respond to trending content or industry voices' },
    { id: 'tt_live', name: 'TikTok Live frequency', category: 'activity', weight: 2, description: '1+ Live/week for accounts with 1k+ followers' },
    { id: 'tt_analytics', name: 'Profile analytics review', category: 'metrics', weight: 3, description: 'Follower activity times used for scheduling, audience demographics' },
  ],
  [Platform.PINTEREST]: [
    { id: 'pin_profile', name: 'Business account & profile', category: 'setup', weight: 3, description: 'Business account, keyword-rich bio, verified website, custom username', aiRewriteEnabled: true },
    { id: 'pin_boards', name: 'Board strategy', category: 'structure', weight: 4, description: '10+ boards, keyword-rich titles and descriptions, relevant covers' },
    { id: 'pin_frequency', name: 'Pin frequency', category: 'activity', weight: 3, description: '5–15 pins/day, mix of own content and repins, consistent timing' },
    { id: 'pin_design', name: 'Pin design quality', category: 'brand', weight: 4, description: '2:3 ratio (1000×1500px), text overlay, brand colors, vertical format' },
    { id: 'pin_titles', name: 'Pin titles & descriptions', category: 'seo', weight: 4, description: '100-char title with keyword first, 500-char description, CTA, hashtags', aiRewriteEnabled: true },
    { id: 'pin_rich_pins', name: 'Rich pins enabled', category: 'setup', weight: 3, description: 'Article, product, or recipe rich pins verified for extra data in feed' },
    { id: 'pin_seo', name: 'Pinterest SEO', category: 'seo', weight: 4, description: 'Keywords in profile name, board titles, pin descriptions — Pinterest is a search engine' },
    { id: 'pin_idea_pins', name: 'Idea pins / video pins', category: 'content', weight: 3, description: 'Multi-page Idea Pins for tutorials, stories, how-tos — higher reach' },
  ],
  [Platform.GOOGLE_ADS]: [
    { id: 'gads_tracking', name: 'Conversion tracking', category: 'setup', weight: 5 },
    { id: 'gads_quality_score', name: 'Quality Score (avg)', category: 'performance', weight: 4, description: 'Target 7+/10. Below 5 means poor ad relevance or landing page experience' },
    { id: 'gads_ad_copy', name: 'Responsive ad headlines', category: 'content', weight: 4, description: '15 headlines, 4 descriptions — all slots filled, pin strategy used', aiRewriteEnabled: true },
    { id: 'gads_keywords', name: 'Keyword match types', category: 'targeting', weight: 4, description: 'Mix of exact, phrase, broad match modifier — no broad match without RLSA' },
    { id: 'gads_negatives', name: 'Negative keyword list', category: 'targeting', weight: 4, description: 'Campaign and ad-group level negatives, search terms reviewed weekly' },
    { id: 'gads_extensions', name: 'Ad extensions / assets', category: 'setup', weight: 3, description: 'Sitelinks, callouts, structured snippets, call, location, image assets all set' },
    { id: 'gads_landing_pages', name: 'Landing page alignment', category: 'ux', weight: 5, description: 'Keyword in URL, H1, and above fold. Page speed > 80 mobile' },
    { id: 'gads_audiences', name: 'Audience targeting & RLSA', category: 'targeting', weight: 3, description: 'Remarketing lists, customer match, similar audiences layered on search' },
    { id: 'gads_bidding', name: 'Smart bidding setup', category: 'strategy', weight: 3, description: 'Target CPA or ROAS with 30+ conversions/month, or Maximize Conversions' },
    { id: 'gads_structure', name: 'Campaign structure', category: 'structure', weight: 3, description: 'Brand vs non-brand separated, SKAGs or tightly themed ad groups' },
  ],
  [Platform.EMAIL]: [
    { id: 'em_auth', name: 'SPF / DKIM / DMARC', category: 'setup', weight: 5 },
    { id: 'em_list', name: 'List hygiene & health', category: 'setup', weight: 4 },
    { id: 'em_subject', name: 'Subject line quality', category: 'content', weight: 5, description: '35–50 chars, no spam triggers, personalization token, A/B tested', aiRewriteEnabled: true },
    { id: 'em_preview', name: 'Preview text', category: 'content', weight: 3, description: '80–120 chars, complements subject line, adds curiosity or urgency', aiRewriteEnabled: true },
    { id: 'em_template', name: 'Email template design', category: 'design', weight: 3, description: 'Mobile-first, 600px max, single column, large CTA button' },
    { id: 'em_cta', name: 'CTA clarity & placement', category: 'conversion', weight: 4, description: 'One primary CTA, above fold, high contrast button, action verb' },
    { id: 'em_personalization', name: 'Personalization depth', category: 'strategy', weight: 3, description: 'First name at minimum, dynamic content blocks by segment' },
    { id: 'em_automation', name: 'Automation sequences', category: 'strategy', weight: 4, description: 'Welcome series (5 emails), nurture, cart abandon, win-back' },
    { id: 'em_frequency', name: 'Send frequency & timing', category: 'strategy', weight: 3, description: 'Consistent cadence, optimal send time (Tue–Thu 9–11am)' },
    { id: 'em_unsubscribe', name: 'Unsubscribe & compliance', category: 'compliance', weight: 4, description: 'One-click unsubscribe, physical address, GDPR/CAN-SPAM compliant' },
    { id: 'em_open_rate', name: 'Open rate vs benchmark', category: 'metrics', weight: 4, description: 'Industry benchmark 20–30%. Below 15% needs subject line or list work' },
    { id: 'em_ctr', name: 'Click-through rate', category: 'metrics', weight: 4, description: 'Benchmark 2–5%. Low CTR = weak CTA or irrelevant content' },
  ],
  [Platform.WHATSAPP]: [
    { id: 'wa_profile', name: 'Business profile completeness', category: 'setup', weight: 4, description: 'Logo, description, email, website, address, category, catalog' },
    { id: 'wa_catalog', name: 'Product/service catalog', category: 'setup', weight: 4, description: 'All products/services listed with images, descriptions, pricing' },
    { id: 'wa_auto_reply', name: 'Automated greeting & away messages', category: 'setup', weight: 3, description: 'Welcome message for new chats, away message for off-hours' },
    { id: 'wa_quick_replies', name: 'Quick replies library', category: 'efficiency', weight: 3, description: '10+ quick replies for FAQs, saves team response time by 60%' },
    { id: 'wa_labels', name: 'Contact labeling system', category: 'crm', weight: 3, description: 'New lead, In progress, Payment pending, Closed — full pipeline visibility' },
    { id: 'wa_broadcast', name: 'Broadcast list strategy', category: 'marketing', weight: 4, description: 'Segmented lists, personalized message templates, opt-in compliance' },
    { id: 'wa_response_time', name: 'Average response time', category: 'metrics', weight: 4, description: 'Target < 5 minutes. Under 1 minute increases conversion by 78%' },
    { id: 'wa_api', name: 'WhatsApp Business API setup', category: 'setup', weight: 3, description: 'API connected for high-volume messaging, CRM integration, chatbot' },
    { id: 'wa_cta', name: 'Click-to-WhatsApp ads', category: 'marketing', weight: 3, description: 'Meta ads with WhatsApp CTA for lead generation' },
  ],
  [Platform.FACEBOOK]: [
    { id: 'fb_page_complete', name: 'Page completeness', category: 'profile', weight: 5, description: 'All sections filled: about, category, phone, website, hours, CTA button set' },
    { id: 'fb_cover', name: 'Cover photo / video', category: 'brand', weight: 3, description: '820×312px cover, updated regularly, brand-aligned, optional short video loop' },
    { id: 'fb_profile_pic', name: 'Profile picture', category: 'brand', weight: 3, description: 'Logo centered, 180×180px, recognisable at small sizes' },
    { id: 'fb_username', name: 'Custom page username', category: 'setup', weight: 2, description: 'facebook.com/yourbrand — short, consistent with other platforms' },
    { id: 'fb_posting', name: 'Post frequency', category: 'activity', weight: 4, description: '5+ posts/week, mix of video, image, link, story' },
    { id: 'fb_reels', name: 'Facebook Reels usage', category: 'content', weight: 4, description: 'At least 2 Reels/week — Reels get highest organic reach on Facebook' },
    { id: 'fb_stories', name: 'Stories frequency', category: 'activity', weight: 3, description: '3–5 stories/day, interactive stickers (polls, questions)' },
    { id: 'fb_engagement', name: 'Engagement rate', category: 'metrics', weight: 4, description: 'Likes + comments + shares / reach — benchmark 1–3%' },
    { id: 'fb_response_time', name: 'Response time to messages', category: 'community', weight: 4, description: '< 1 hour response time; "Very responsive" badge threshold is 90% within 15 min' },
    { id: 'fb_reviews', name: 'Reviews rating & responses', category: 'trust', weight: 5, description: '4.5+ stars, all reviews responded to within 24h, review link shared actively' },
    { id: 'fb_groups', name: 'Facebook Group strategy', category: 'community', weight: 3, description: 'Brand-owned group or active engagement in niche groups' },
    { id: 'fb_ads_pixel', name: 'Meta Pixel installed', category: 'tracking', weight: 5, description: 'Pixel firing on all key pages, events configured (ViewContent, AddToCart, Purchase)' },
    { id: 'fb_retargeting', name: 'Retargeting campaigns active', category: 'ads', weight: 4, description: 'Website visitor retargeting, engagement retargeting, and lookalike audiences running' },
  ],
};
