import nodemailer from 'nodemailer';
import { prisma } from '../lib/prisma';
import { decrypt, isEncrypted } from '../lib/encryption';

async function getTransport(agencyId: string) {
  const agency = await prisma.agency.findUnique({ where: { id: agencyId } });
  if (!agency?.smtpHost || !agency?.smtpUser || !agency?.smtpPass) {
    throw Object.assign(new Error('SMTP not configured. Add email settings in Settings → API Keys.'), { statusCode: 400 });
  }
  const pass = isEncrypted(agency.smtpPass) ? decrypt(agency.smtpPass) : agency.smtpPass;
  const transport = nodemailer.createTransport({
    host: agency.smtpHost,
    port: 587,
    secure: false,
    auth: { user: agency.smtpUser, pass },
  });
  return { transport, fromEmail: agency.smtpUser, agencyName: agency.name };
}

export async function sendClientReport(params: {
  agencyId: string;
  clientName: string;
  contactEmail: string;
  pdfBuffer: Buffer;
  filename: string;
  monthLabel: string;
}) {
  const { transport, fromEmail, agencyName } = await getTransport(params.agencyId);
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.contactEmail,
    subject: `${params.clientName} — ${params.monthLabel} Performance Report`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px;font-weight:700">${agencyName}</h1>
          <p style="color:#a7f3d0;margin:4px 0 0;font-size:13px">Monthly Performance Report</p>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">Hi ${params.clientName} team,</p>
          <p style="color:#374151;font-size:14px;line-height:1.6">
            Your <strong>${params.monthLabel}</strong> performance report is attached.
            It covers your platform optimization scores, content activity, and audit results for the month.
          </p>
          <p style="color:#374151;font-size:14px;line-height:1.6">
            Have questions about the report? Reply to this email and we'll be happy to walk you through it.
          </p>
          <p style="color:#6b7280;font-size:13px;margin-top:24px">Best regards,<br><strong>${agencyName}</strong></p>
        </div>
      </div>
    `,
    attachments: [{
      filename: params.filename,
      content: params.pdfBuffer,
      contentType: 'application/pdf',
    }],
  });
}

export async function sendDigestEmail(params: {
  agencyId: string;
  ownerEmail: string;
  ownerName: string;
  weekLabel: string;
  digestHtml: string;
}) {
  const { transport, fromEmail, agencyName } = await getTransport(params.agencyId);
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.ownerEmail,
    subject: `Agency Digest — ${params.weekLabel}`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:620px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px;font-weight:700">${agencyName}</h1>
          <p style="color:#a7f3d0;margin:4px 0 0;font-size:13px">AI Weekly Digest · ${params.weekLabel}</p>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">Hi ${params.ownerName},</p>
          <div style="color:#374151;font-size:14px;line-height:1.7;white-space:pre-wrap">${params.digestHtml}</div>
          <p style="color:#6b7280;font-size:12px;margin-top:24px;padding-top:16px;border-top:1px solid #f3f4f6">
            Generated by Agency OS · AI Weekly Digest
          </p>
        </div>
      </div>
    `,
  });
}
