import nodemailer from 'nodemailer';
import { prisma } from '../lib/prisma';
import { decrypt, isEncrypted } from '../lib/encryption';

async function getTransport(agencyId: string) {
  const agency = await prisma.agency.findUnique({ where: { id: agencyId } });
  if (!agency?.smtpHost || !agency?.smtpUser || !agency?.smtpPass) {
    throw Object.assign(new Error('SMTP not configured. Add email settings in Settings → API Keys.'), { statusCode: 400 });
  }
  const pass = isEncrypted(agency.smtpPass) ? decrypt(agency.smtpPass) : agency.smtpPass;
  const transport = nodemailer.createTransport({
    host: agency.smtpHost,
    port: 587,
    secure: false,
    auth: { user: agency.smtpUser, pass },
  });
  return { transport, fromEmail: agency.smtpUser, agencyName: agency.name };
}

export async function sendClientReport(params: {
  agencyId: string;
  clientName: string;
  contactEmail: string;
  pdfBuffer: Buffer;
  filename: string;
  monthLabel: string;
}) {
  const { transport, fromEmail, agencyName } = await getTransport(params.agencyId);
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.contactEmail,
    subject: `${params.clientName} — ${params.monthLabel} Performance Report`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px;font-weight:700">${agencyName}</h1>
          <p style="color:#a7f3d0;margin:4px 0 0;font-size:13px">Monthly Performance Report</p>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">Hi ${params.clientName} team,</p>
          <p style="color:#374151;font-size:14px;line-height:1.6">
            Your <strong>${params.monthLabel}</strong> performance report is attached.
            It covers your platform optimization scores, content activity, and audit results for the month.
          </p>
          <p style="color:#374151;font-size:14px;line-height:1.6">
            Have questions about the report? Reply to this email and we'll be happy to walk you through it.
          </p>
          <p style="color:#6b7280;font-size:13px;margin-top:24px">Best regards,<br><strong>${agencyName}</strong></p>
        </div>
      </div>
    `,
    attachments: [{
      filename: params.filename,
      content: params.pdfBuffer,
      contentType: 'application/pdf',
    }],
  });
}

export async function sendDigestEmail(params: {
  agencyId: string;
  ownerEmail: string;
  ownerName: string;
  weekLabel: string;
  digestHtml: string;
}) {
  const { transport, fromEmail, agencyName } = await getTransport(params.agencyId);
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.ownerEmail,
    subject: `Agency Digest — ${params.weekLabel}`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:620px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px;font-weight:700">${agencyName}</h1>
          <p style="color:#a7f3d0;margin:4px 0 0;font-size:13px">AI Weekly Digest · ${params.weekLabel}</p>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">Hi ${params.ownerName},</p>
          <div style="color:#374151;font-size:14px;line-height:1.7;white-space:pre-wrap">${params.digestHtml}</div>
          <p style="color:#6b7280;font-size:12px;margin-top:24px;padding-top:16px;border-top:1px solid #f3f4f6">
            Generated by Agency OS · AI Weekly Digest
          </p>
        </div>
      </div>
    `,
  });
}

export async function sendMessageEmail(params: {
  agencyId: string;
  clientId: string;
  senderRole: string;
  body: string;
}) {
  const { agencyId, clientId, senderRole, body } = params;
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(agencyId));
  } catch {
    return;
  }

  if (senderRole === 'CLIENT') {
    const assignment = await prisma.clientAssignment.findFirst({
      where: { clientId, client: { agencyId } },
      include: { user: { select: { email: true, name: true } } },
    });
    if (!assignment?.user?.email) return;
    await transport.sendMail({
      from: `"${agencyName}" <${fromEmail}>`,
      to: assignment.user.email,
      subject: `New message from client`,
      html: `<p>Your client sent a new message:</p><blockquote style="border-left:3px solid #e5e7eb;padding-left:12px;color:#374151">${body.replace(/\n/g, '<br>')}</blockquote><p><a href="${process.env.APP_URL ?? ''}/clients/${clientId}">View conversation →</a></p>`,
    });
  } else {
    const client = await prisma.client.findFirst({ where: { id: clientId, agencyId }, select: { contactEmail: true, name: true } });
    if (!client?.contactEmail) return;
    await transport.sendMail({
      from: `"${agencyName}" <${fromEmail}>`,
      to: client.contactEmail,
      subject: `New message from ${agencyName}`,
      html: `<p>You have a new message from your account team:</p><blockquote style="border-left:3px solid #e5e7eb;padding-left:12px;color:#374151">${body.replace(/\n/g, '<br>')}</blockquote><p>Log in to your portal to reply.</p>`,
    });
  }
}

export async function sendActionItemEmail(params: {
  agencyId: string;
  clientEmail: string;
  clientName: string;
  title: string;
  description?: string;
  dueDate?: Date;
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.clientEmail,
    subject: `Action Required: ${params.title}`,
    html: `<p>Hi ${params.clientName},</p><p>Your account team has created an action item for you:</p><h3>${params.title}</h3>${params.description ? `<p>${params.description}</p>` : ''}${params.dueDate ? `<p><strong>Due:</strong> ${params.dueDate.toLocaleDateString()}</p>` : ''}<p>Log in to your portal to view and complete it.</p>`,
  });
}

export async function sendOnboardingEmail(params: {
  agencyId: string;
  clientName: string;
  contactEmail: string;
  token: string;
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  const baseUrl = (process.env.APP_URL ?? 'https://nedsdrishti.in').replace(/\/$/, '');
  const url = `${baseUrl}/onboarding/${params.token}`;
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.contactEmail,
    subject: `Welcome to ${agencyName} — Complete your onboarding`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px">${agencyName}</h1>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p>Hi ${params.clientName} team,</p>
          <p>To get started, please complete your onboarding questionnaire. It takes about 5 minutes and helps us set up your account correctly.</p>
          <p style="text-align:center;margin:28px 0">
            <a href="${url}" style="background:#1a472a;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:600">Complete Onboarding →</a>
          </p>
          <p style="color:#6b7280;font-size:13px">This link expires in 7 days. If you have any questions, reply to this email.</p>
        </div>
      </div>
    `,
  });
}
