import nodemailer from 'nodemailer';
import { prisma } from '../lib/prisma';
import { decrypt, isEncrypted } from '../lib/encryption';

async function getTransport(agencyId: string) {
  const agency = await prisma.agency.findUnique({ where: { id: agencyId } });
  if (!agency?.smtpHost || !agency?.smtpUser || !agency?.smtpPass) {
    throw Object.assign(new Error('SMTP not configured. Add email settings in Settings → API Keys.'), { statusCode: 400 });
  }
  const pass = isEncrypted(agency.smtpPass) ? decrypt(agency.smtpPass) : agency.smtpPass;
  const transport = nodemailer.createTransport({
    host: agency.smtpHost,
    port: 587,
    secure: false,
    auth: { user: agency.smtpUser, pass },
  });
  return { transport, fromEmail: agency.smtpUser, agencyName: agency.name };
}

export async function sendClientReport(params: {
  agencyId: string;
  clientName: string;
  contactEmail: string;
  pdfBuffer: Buffer;
  filename: string;
  monthLabel: string;
}) {
  const { transport, fromEmail, agencyName } = await getTransport(params.agencyId);
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.contactEmail,
    subject: `${params.clientName} — ${params.monthLabel} Performance Report`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px;font-weight:700">${agencyName}</h1>
          <p style="color:#a7f3d0;margin:4px 0 0;font-size:13px">Monthly Performance Report</p>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">Hi ${params.clientName} team,</p>
          <p style="color:#374151;font-size:14px;line-height:1.6">
            Your <strong>${params.monthLabel}</strong> performance report is attached.
            It covers your platform optimization scores, content activity, and audit results for the month.
          </p>
          <p style="color:#374151;font-size:14px;line-height:1.6">
            Have questions about the report? Reply to this email and we'll be happy to walk you through it.
          </p>
          <p style="color:#6b7280;font-size:13px;margin-top:24px">Best regards,<br><strong>${agencyName}</strong></p>
        </div>
      </div>
    `,
    attachments: [{
      filename: params.filename,
      content: params.pdfBuffer,
      contentType: 'application/pdf',
    }],
  });
}

export async function sendDigestEmail(params: {
  agencyId: string;
  ownerEmail: string;
  ownerName: string;
  weekLabel: string;
  digestHtml: string;
}) {
  const { transport, fromEmail, agencyName } = await getTransport(params.agencyId);
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.ownerEmail,
    subject: `Agency Digest — ${params.weekLabel}`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:620px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px;font-weight:700">${agencyName}</h1>
          <p style="color:#a7f3d0;margin:4px 0 0;font-size:13px">AI Weekly Digest · ${params.weekLabel}</p>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">Hi ${params.ownerName},</p>
          <div style="color:#374151;font-size:14px;line-height:1.7;white-space:pre-wrap">${params.digestHtml}</div>
          <p style="color:#6b7280;font-size:12px;margin-top:24px;padding-top:16px;border-top:1px solid #f3f4f6">
            Generated by Agency OS · AI Weekly Digest
          </p>
        </div>
      </div>
    `,
  });
}

export async function sendMessageEmail(params: {
  agencyId: string;
  clientId: string;
  senderRole: string;
  body: string;
}) {
  const { agencyId, clientId, senderRole, body } = params;
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(agencyId));
  } catch {
    return;
  }

  if (senderRole === 'CLIENT') {
    const assignment = await prisma.clientAssignment.findFirst({
      where: { clientId, client: { agencyId } },
      include: { user: { select: { email: true, name: true } } },
    });
    if (!assignment?.user?.email) return;
    await transport.sendMail({
      from: `"${agencyName}" <${fromEmail}>`,
      to: assignment.user.email,
      subject: `New message from client`,
      html: `<p>Your client sent a new message:</p><blockquote style="border-left:3px solid #e5e7eb;padding-left:12px;color:#374151">${body.replace(/\n/g, '<br>')}</blockquote><p><a href="${process.env.APP_URL ?? ''}/clients/${clientId}">View conversation →</a></p>`,
    });
  } else {
    const client = await prisma.client.findFirst({ where: { id: clientId, agencyId }, select: { contactEmail: true, name: true } });
    if (!client?.contactEmail) return;
    await transport.sendMail({
      from: `"${agencyName}" <${fromEmail}>`,
      to: client.contactEmail,
      subject: `New message from ${agencyName}`,
      html: `<p>You have a new message from your account team:</p><blockquote style="border-left:3px solid #e5e7eb;padding-left:12px;color:#374151">${body.replace(/\n/g, '<br>')}</blockquote><p>Log in to your portal to reply.</p>`,
    });
  }
}

export async function sendActionItemEmail(params: {
  agencyId: string;
  clientEmail: string;
  clientName: string;
  title: string;
  description?: string;
  dueDate?: Date;
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.clientEmail,
    subject: `Action Required: ${params.title}`,
    html: `<p>Hi ${params.clientName},</p><p>Your account team has created an action item for you:</p><h3>${params.title}</h3>${params.description ? `<p>${params.description}</p>` : ''}${params.dueDate ? `<p><strong>Due:</strong> ${params.dueDate.toLocaleDateString()}</p>` : ''}<p>Log in to your portal to view and complete it.</p>`,
  });
}

export async function sendContentReviewEmail(params: {
  agencyId: string;
  amEmail: string;
  clientName: string;
  action: 'CLIENT_APPROVED' | 'CHANGES_REQUESTED';
  caption: string;
  feedback?: string;
  postId: string;
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  const baseUrl = (process.env.APP_URL ?? 'https://nedsdrishti.in').replace(/\/$/, '');
  const isApproved = params.action === 'CLIENT_APPROVED';
  const subject = isApproved
    ? `✅ ${params.clientName} approved a post`
    : `💬 ${params.clientName} requested changes on a post`;
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.amEmail,
    subject,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;color:#111827">
        <div style="background:${isApproved ? '#166534' : '#92400e'};padding:24px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:18px;font-weight:700">${agencyName}</h1>
          <p style="color:${isApproved ? '#bbf7d0' : '#fde68a'};margin:4px 0 0;font-size:13px">Content Review</p>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">
            ${isApproved
              ? `<strong>${params.clientName}</strong> has <span style="color:#16a34a;font-weight:600">approved</span> a post.`
              : `<strong>${params.clientName}</strong> has <span style="color:#d97706;font-weight:600">requested changes</span> on a post.`}
          </p>
          <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:14px 16px;margin:16px 0">
            <p style="color:#6b7280;font-size:12px;margin:0 0 6px;font-weight:600;text-transform:uppercase;letter-spacing:.05em">Caption preview</p>
            <p style="color:#111827;font-size:14px;margin:0;line-height:1.5">${params.caption.slice(0, 200)}${params.caption.length > 200 ? '…' : ''}</p>
          </div>
          ${params.feedback ? `
          <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:14px 16px;margin:16px 0">
            <p style="color:#92400e;font-size:12px;margin:0 0 6px;font-weight:600;text-transform:uppercase;letter-spacing:.05em">Client feedback</p>
            <p style="color:#78350f;font-size:14px;margin:0;line-height:1.5">${params.feedback}</p>
          </div>` : ''}
          <p style="text-align:center;margin:24px 0">
            <a href="${baseUrl}/content/${params.postId}/edit" style="background:#1a472a;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px">View Post →</a>
          </p>
        </div>
      </div>
    `,
  });
}

export async function sendOnboardingEmail(params: {
  agencyId: string;
  clientName: string;
  contactEmail: string;
  token: string;
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  const baseUrl = (process.env.APP_URL ?? 'https://nedsdrishti.in').replace(/\/$/, '');
  const url = `${baseUrl}/onboarding/${params.token}`;
  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.contactEmail,
    subject: `Welcome to ${agencyName} — Complete your onboarding`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;color:#111827">
        <div style="background:#1a472a;padding:28px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:20px">${agencyName}</h1>
        </div>
        <div style="background:#fff;padding:28px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p>Hi ${params.clientName} team,</p>
          <p>To get started, please complete your onboarding questionnaire. It takes about 5 minutes and helps us set up your account correctly.</p>
          <p style="text-align:center;margin:28px 0">
            <a href="${url}" style="background:#1a472a;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:600">Complete Onboarding →</a>
          </p>
          <p style="color:#6b7280;font-size:13px">This link expires in 7 days. If you have any questions, reply to this email.</p>
        </div>
      </div>
    `,
  });
}

// ─── Smart Alert Emails ───────────────────────────────────────────────────────

export async function sendPendingApprovalDigest(params: {
  agencyId: string;
  recipientEmails: string[];
  posts: { caption: string; clientName: string; hoursAgo: number; id: string }[];
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  const baseUrl = (process.env.APP_URL ?? 'https://nedsdrishti.in').replace(/\/$/, '');
  const rows = params.posts.map(p => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#374151">${p.caption.slice(0, 90)}${p.caption.length > 90 ? '…' : ''}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#6b7280;white-space:nowrap">${p.clientName}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#d97706;white-space:nowrap;font-weight:600">${p.hoursAgo}h ago</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6"><a href="${baseUrl}/content/${p.id}/edit" style="color:#1a472a;font-size:12px;font-weight:600">Review →</a></td>
    </tr>
  `).join('');

  for (const to of params.recipientEmails) {
    await transport.sendMail({
      from: `"${agencyName}" <${fromEmail}>`,
      to,
      subject: `⏳ ${params.posts.length} post${params.posts.length > 1 ? 's' : ''} waiting for approval over 24 hours`,
      html: `
        <div style="font-family:system-ui,sans-serif;max-width:620px;margin:0 auto;color:#111827">
          <div style="background:#92400e;padding:24px 32px;border-radius:12px 12px 0 0">
            <h1 style="color:#fff;margin:0;font-size:18px;font-weight:700">${agencyName}</h1>
            <p style="color:#fde68a;margin:4px 0 0;font-size:13px">Approval Reminder</p>
          </div>
          <div style="background:#fff;padding:24px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
            <p style="color:#374151;font-size:15px">The following posts have been waiting for your approval for more than 24 hours:</p>
            <table style="width:100%;border-collapse:collapse;margin:16px 0">
              <thead>
                <tr style="background:#f9fafb">
                  <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Caption</th>
                  <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Client</th>
                  <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Waiting</th>
                  <th style="padding:8px 12px"></th>
                </tr>
              </thead>
              <tbody>${rows}</tbody>
            </table>
            <p style="text-align:center;margin:20px 0">
              <a href="${baseUrl}/content" style="background:#1a472a;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px">Go to Content Studio →</a>
            </p>
          </div>
        </div>
      `,
    }).catch(() => {});
  }
}

export async function sendOverdueItemsDigest(params: {
  agencyId: string;
  recipientEmails: string[];
  items: { title: string; clientName: string; clientId: string; dueDate: Date }[];
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  const baseUrl = (process.env.APP_URL ?? 'https://nedsdrishti.in').replace(/\/$/, '');
  const rows = params.items.map(item => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#374151">${item.title}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#6b7280">${item.clientName}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#dc2626;font-weight:600">${item.dueDate.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6"><a href="${baseUrl}/clients/${item.clientId}" style="color:#1a472a;font-size:12px;font-weight:600">View →</a></td>
    </tr>
  `).join('');

  for (const to of params.recipientEmails) {
    await transport.sendMail({
      from: `"${agencyName}" <${fromEmail}>`,
      to,
      subject: `⚠️ ${params.items.length} action item${params.items.length > 1 ? 's are' : ' is'} overdue`,
      html: `
        <div style="font-family:system-ui,sans-serif;max-width:620px;margin:0 auto;color:#111827">
          <div style="background:#7f1d1d;padding:24px 32px;border-radius:12px 12px 0 0">
            <h1 style="color:#fff;margin:0;font-size:18px;font-weight:700">${agencyName}</h1>
            <p style="color:#fca5a5;margin:4px 0 0;font-size:13px">Action Items Overdue</p>
          </div>
          <div style="background:#fff;padding:24px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
            <p style="color:#374151;font-size:15px">The following action items have passed their due date and need attention:</p>
            <table style="width:100%;border-collapse:collapse;margin:16px 0">
              <thead>
                <tr style="background:#fef2f2">
                  <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Task</th>
                  <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Client</th>
                  <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Due</th>
                  <th style="padding:8px 12px"></th>
                </tr>
              </thead>
              <tbody>${rows}</tbody>
            </table>
            <p style="text-align:center;margin:20px 0">
              <a href="${baseUrl}/dashboard" style="background:#1a472a;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px">Go to Dashboard →</a>
            </p>
          </div>
        </div>
      `,
    }).catch(() => {});
  }
}

export async function sendInvoiceOverdueAlert(params: {
  agencyId: string;
  ownerEmail: string;
  invoices: { invoiceNumber: string; clientName: string; total: number; currency: string; dueDate: Date; id: string }[];
}) {
  let transport: ReturnType<typeof nodemailer.createTransport>;
  let fromEmail: string;
  let agencyName: string;
  try {
    ({ transport, fromEmail, agencyName } = await getTransport(params.agencyId));
  } catch {
    return;
  }
  const baseUrl = (process.env.APP_URL ?? 'https://nedsdrishti.in').replace(/\/$/, '');
  const rows = params.invoices.map(inv => {
    const daysOverdue = Math.floor((Date.now() - inv.dueDate.getTime()) / 86_400_000);
    return `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#374151;font-weight:600">${inv.invoiceNumber}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#374151">${inv.clientName}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#374151">${inv.currency} ${inv.total.toLocaleString('en-IN')}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6;font-size:13px;color:#dc2626;font-weight:600">${daysOverdue}d overdue</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f3f4f6"><a href="${baseUrl}/invoices/${inv.id}" style="color:#1a472a;font-size:12px;font-weight:600">View →</a></td>
    </tr>
  `}).join('');

  await transport.sendMail({
    from: `"${agencyName}" <${fromEmail}>`,
    to: params.ownerEmail,
    subject: `💸 ${params.invoices.length} invoice${params.invoices.length > 1 ? 's are' : ' is'} overdue — action required`,
    html: `
      <div style="font-family:system-ui,sans-serif;max-width:620px;margin:0 auto;color:#111827">
        <div style="background:#1e3a5f;padding:24px 32px;border-radius:12px 12px 0 0">
          <h1 style="color:#fff;margin:0;font-size:18px;font-weight:700">${agencyName}</h1>
          <p style="color:#93c5fd;margin:4px 0 0;font-size:13px">Invoice Payment Reminder</p>
        </div>
        <div style="background:#fff;padding:24px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
          <p style="color:#374151;font-size:15px">The following invoices are past their due date and payment has not been received:</p>
          <table style="width:100%;border-collapse:collapse;margin:16px 0">
            <thead>
              <tr style="background:#eff6ff">
                <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Invoice #</th>
                <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Client</th>
                <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Amount</th>
                <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.05em">Status</th>
                <th style="padding:8px 12px"></th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>
          <p style="text-align:center;margin:20px 0">
            <a href="${baseUrl}/invoices" style="background:#1a472a;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px">Go to Invoices →</a>
          </p>
          <p style="color:#6b7280;font-size:12px;margin-top:16px">Consider following up with the client directly or sending a payment reminder.</p>
        </div>
      </div>
    `,
  });
}
